name: DOTNET deploy

on:
  push:
    branches:
      - master

jobs:
  primer-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Run ls command
        run: ls -la

      - name: Docker ps
        run: docker ps

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repository content
        run: ls
